# Generated by Django 5.0.3 on 2024-03-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('bookID', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=50)),
                ('authorname', models.CharField(max_length=50)),
                ('dopublication', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
